# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d514489aa11c868b877e13ffb6f4c2da436f0c705a4f2b81f33f986802bd2b27ff6801806bce3c8652c3f78f55d8ab4e58e6d670b3441e0af81ff70f3f38fdcb

test:
  secret_key_base: d3ed0e44f615ed7d1e97d43168811e7602929279756fdf35b25d4b3fcddcd282de29479113a13610f95f59747b89fbfe69081855a014a5d05cb3e4af9bdc2206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
